### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by kenhorlador** [Ashutosh00710/github-readme-activity-graph#109]
**Describe the bug**
The app seems to be not working. The link (https://activity-graph.herokuapp.com/graph?username=kenhorlador&hide_border=false&area=true&bg_color=2E0655) is not reachable in anyway.

**Expected behavior**
I expected that the graph would show up but 'Application error' seems to be showing up in the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/65501588/155874803-3977acde-9690-45d9-a6c5-6fa7ed8e51a6.png)

**Comment by Ashutosh00710** [comment]
Refer to #55 
Things are up and running now
