### ISSUE TITLE
BUG: Application Error

### ISSUE THREAD

**Issue by Dynesshely** [Ashutosh00710/github-readme-activity-graph#110]
**Describe the bug**
In time of UTC+08:00 on 2022-02-27 21:03 , your application on herokuapp.com had error.<br>
The link of image is: https://activity-graph.herokuapp.com/graph?username=Dynesshely&theme=react-dark<br>

**To Reproduce**
😅

**Expected behavior**
Return the correct image.

**Screenshots**
![image](https://user-images.githubusercontent.com/50760269/155883622-cc9faf1d-15a9-4abc-a30d-f89c0fe62c95.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Build 22000.527
 - Browser Edge & Chrome (Both get same result)
 - Version Latest stable

**Smartphone (please complete the following information):**
😅

**Additional context**
😅

**Comment by harlexkhal** [comment]
Yeah same issue but there is a guide to deploy the project to your own heroku account [here](https://github.com/Ashutosh00710/github-readme-activity-graph#Deploy-on-your-own-heroku-instance)

**Comment by Ashutosh00710** [comment]
Refer to #55

**Comment by Ashutosh00710** [comment]
But things are up and running now

**Comment by Dynesshely** [comment]
> Yeah same issue but there is a guide to deploy the project to your own heroku account [here](https://github.com/Ashutosh00710/github-readme-activity-graph#Deploy-on-your-own-heroku-instance)

Thanks for this.
But for my WEB environment (yeah, i'm chinese), you konw.
I would deploy it when I got a VPN (it's hard in China)
Thanks for your works 😉

**Comment by Ashutosh00710** [comment]
No issues @Dynesshely, sorry interruption. Enjoy the graph buddy 😄
