### ISSUE TITLE
BUG: Application Error

### ISSUE THREAD

**Issue by kenhorlador** [Ashutosh00710/github-readme-activity-graph#114]
**Describe the bug**
The application is not working. 
![image](https://user-images.githubusercontent.com/65501588/159879911-17d9d35a-cadf-412c-802a-c5d8d70df1a0.png)

The link: "https://activity-graph.herokuapp.com/" is not reachable.

**Comment by antonhibl** [comment]
I am also having the same issue after following the steps to host my own Heroku instance.

**Comment by Ashutosh00710** [comment]
The graph is up and running now. Check #55
