### ISSUE TITLE
BUG: The Server of the activity server isn't working. Please fix this

### ISSUE THREAD

**Issue by programmer-saidur** [Ashutosh00710/github-readme-activity-graph#124]
![image](https://user-images.githubusercontent.com/74282142/170170612-054c311d-aec2-4eba-909a-4a6f11d0c977.png)

**Comment by TechWiz-3** [comment]
Yup, same here

**Comment by Ashutosh00710** [comment]
Refer #55, Project is up now. Closing the issue
