### ISSUE TITLE
BUG: Custom Heroku instance does not work

### ISSUE THREAD

**Issue by krakxn** [Ashutosh00710/github-readme-activity-graph#133]
It was working fine for me all this time -- but today apparently, without any changes, it just is not working.

*Note: I tried both the common Heroku activity-graph and also my own activity-graph hosted on Heroku -- both seem to not work.*

What could be the issue here? You can take a further look at my profile's Readme, you can check it directly too but I have listed it below to keep this concise -- code below:

Mine/Custom instance hosted on Heroku:
```
[![AN's GitHub Activity Graph](https://krakxn-activity-graph.herokuapp.com/graph?username=krakxn&bg_color=000502&color=ffffff&line=ffffff&hide_border=true)](https://github.com/ashutosh00710/github-readme-activity-graph)
```

Even the sample code does not seem to work:
```
[![Ashutosh's github activity graph](https://activity-graph.herokuapp.com/graph?username=Ashutosh00710)](https://github.com/ashutosh00710/github-readme-activity-graph)
```

Thank you!

**Comment by R3dian** [comment]
Hi @krakxn, it appears to be that free dyno hours for this month are already consumed for activity-graph. My own heroku activity graph is working fine.

**Comment by krakxn** [comment]
I see -- but why is my own activity graph down too? Could you look into it?

**Comment by iamstan13y** [comment]
HI @krakxn I think the only option we have is to deploy our own instances on Heroku. Since your activity graph is dependant on the instance deployed by the original author

**Comment by krakxn** [comment]
Yes yes I understand -- but my own instance is not working too, that is the doubt.

**Comment by R3dian** [comment]
> I see, thank you -- but why is my own activity graph down too? Could you look into it?

I can see that your app is up and running. May be check your token in the config app?

**Comment by krakxn** [comment]
![github-configvar](https://user-images.githubusercontent.com/108299225/180993037-7024cfb5-d29d-4497-9c03-df8db30c7c39.png)

Is this okay? The token is input where the placeholder text was `Key`, with `Value as empty` (Note: the line is to blur the private token)

**Comment by R3dian** [comment]
Key should be TOKEN and value should be the token value get from github.

**Comment by krakxn** [comment]
@R3dian 

Is this okay?

![github-configvar2](https://user-images.githubusercontent.com/108299225/181014724-741d23a6-735f-4adf-a301-47a2275d3425.png)

**Comment by R3dian** [comment]
Looks good and I can see that Graph is also working now.

**Comment by krakxn** [comment]
@R3dian Thank you! It is working now.

Doubt: if in my README.md -- I just have the custom Heroku instance, if it is working now does that mean my instance is fine now?

**Comment by Ashutosh00710** [comment]
@krakxn, Its working now, I have deployed a new instance. The reason is [mentioned](https://github.com/Ashutosh00710/github-readme-activity-graph/issues/133#issuecomment-1195252550) by @R3dian. 

PS: I don't have enough funds to run the server 😂

**Comment by krakxn** [comment]
Mhm.. it does not seem to work again. Any idea as to why my custom instance does not work, even after tweaking the config-vars?

**Comment by Ashutosh00710** [comment]
It seems like your custom instance is working. When I refreshed my browser on your profile it worked and I was able to see the graph.

![image](https://user-images.githubusercontent.com/42907572/181138312-b11ee137-131e-4bca-bf44-c40ef2f83474.png)

And this nature looks like, **Idling**
"In the Heroku free apps the dynos seem to keep idling"

**Comment by krakxn** [comment]
@Ashutosh00710 I see, would this solution work? https://stackoverflow.com/a/5482285

**Comment by Ashutosh00710** [comment]
To be honest I don't have any idea about it. You can use our server url if you want your graph running all the time.

OR

You can deploy on [Repl.it](https://github.com/Ashutosh00710/github-readme-activity-graph#deploy-on-your-own-replit-instance) as well

**Comment by R3dian** [comment]
As @Ashutosh00710 suggested you can also use Repl.it but as far as I know they are also not always awake for free tier. You can give it a try using this one already created.

https://activity-graph.r3dian.repl.co/graph?username=krakxn
