### ISSUE TITLE
The graph doesn't seem to load at all. 

### ISSUE THREAD

**Issue by SourinMajumdar** [Ashutosh00710/github-readme-activity-graph#135]
Tried a lot but it does not load. The URLs etc are properly put, last evening everything was alright.

**Comment by infratidev** [comment]
@SourinMajumdar I was having the same issue. Deploy on heroku, it's very easy and free.

**Comment by EleoXDA** [comment]
> @SourinMajumdar I was having the same issue. Deploy on heroku, it's very easy and free.

Could you navigate us?

**Comment by EleoXDA** [comment]
> @SourinMajumdar I was having the same issue. Deploy on heroku, it's very easy and free.

Do you mean doing these procedures?
https://devcenter.heroku.com/articles/git

**Comment by infratidev** [comment]
Just following the guide is simple: 
https://github.com/Ashutosh00710/github-readme-activity-graph#deploy-on-your-own-heroku-instance

**Comment by Ashutosh00710** [comment]
Refer to #55 . Now everything is up and running 🚀
