### ISSUE TITLE
IMPORTANT: Heroku is no longer offering free plans

### ISSUE THREAD

**Issue by MagicLike** [Ashutosh00710/github-readme-activity-graph#138]
**Is your feature request related to a problem? Please describe.**
Heroku is no longer offering free plans.

**Describe the solution you'd like**
Another way of hosting Github Readme Activity Graph, like Vercel & Docker.

**Comment by Ashutosh00710** [comment]
@MagicLike, thanks for bringing our attention to it. 

We are also thinking about other alternatives. But for existing users we are planning to send a highlighted text (with a message: "**the domain for this graph will expire after October 2022 please migrate it to xyz.url**") along with the graph.

What's your take on this?

**Comment by DenverCoder1** [comment]
@Ashutosh00710 There's still a chance Heroku will sponsor open source projects, nonprofits, and student projects. You may want to look into this. The details are not finalized as far as how much if not 100% discount, or which projects are eligible, but I'd at least recommended waiting to hear more on this. There's an email you can contact for the Salesforce Open Source Program office and they can keep you updated.

From the latest I've heard from them, they expect to have things finalized before Dreamforce (September 20-22).

More info: https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

**Comment by Ashutosh00710** [comment]
@DenverCoder1 Thanks for your concern, I am really grateful to that.
I guess we should email the **Salesforce Open Source Program** team to analyze the project and provide a free tier to us.

**Comment by DenverCoder1** [comment]
@Ashutosh00710 Out of curiosity, did you end up hearing back from the Salesforce Open Source Program?
I haven't heard anything since my initial email to them even after I tried following up with them around the end of September.

**Comment by Ashutosh00710** [comment]
@DenverCoder1 even I haven't got any reply. Was thinking about changing the domain.

**Comment by DenverCoder1** [comment]
Yeah, that's unfortunate. Maybe after the Nov 28 deadline it will be easier to get a hold of them.

I'm moving most of my apps away from Heroku, but the few that still have a lot of users on the herokuapp.com domain, I might keep at least a little longer, but I might move those away too eventually.

I really like using Heroku, but Vercel and fly.io seem to be good free alternatives, although not quite the same.

**Comment by DenverCoder1** [comment]
Interestingly enough, I happened to receive an email linking to a form for requesting open source Heroku credit just about an hour ago. You may have gotten the same email or will likely soon if you messaged them.

**Comment by Ashutosh00710** [comment]
That's great @DenverCoder1. BTW on which email you've sent your email?

**Comment by DenverCoder1** [comment]
I sent an email to ospo-heroku-credits@salesforce.com at the beginning of September and was told they were still finalizing criteria and they would contact when they are ready.

The email I received from Heroku yesterday had a link to this Google Form - https://hello.heroku.com/e/36622/ymKtTTTu3UgGMA5x6/m5pqwq/1156219392?h=prLOSbqh-hJzGNOAKtussfEQ92b4_lnFAcltr_lL2gY

**Comment by Ashutosh00710** [comment]
Thanks @DenverCoder1 for the help. I guess this is a general form to apply for open source project, can I fill this form as well? Because I haven't recieved any response till now.

**Comment by DenverCoder1** [comment]
I can't say for certain, but it definitely looks like a general form that they'd have sent out to everyone. Feel free to try using the link. I've filled it out but haven't heard anything back yet and I expect they could even take a week or so to respond. The form is open until the 30th.

**Comment by jgphilpott** [comment]
Thanks @Ashutosh00710! ... just an FYI though, I think you mistakenly included `https://` twice in the old domain.

**Comment by Ashutosh00710** [comment]
@jgphilpott, as always great catch. I have updated the readme you can check now.
Thanks for your support ❤️. I appreciate it 😊
