### ISSUE TITLE
NEW FEATURE: Title Padding

### ISSUE THREAD

**Issue by zul-m** [Ashutosh00710/github-readme-activity-graph#141]
**Is your feature request related to a problem? Please describe.**
The title seems to have less space below the border whenever we view it on mobile devices.

**Describe the solution you'd like**
A minor feature, but it's good to have the ability to configure the title padding from the border.

**Describe alternatives you've considered**
Make it the default padding value for all themes.

**Additional context**
![image](https://user-images.githubusercontent.com/39239497/189846196-d70a2d6b-07c9-4250-bbf5-96548ff7ff18.png)

**Comment by Rituraj-13** [comment]
Hey, I want to work on this issue. Can you please assign me for this?

**Comment by Kshitij978** [comment]
@Rituraj-13 Sure, go ahead!

**Comment by Kshitij978** [comment]
Hi @Rituraj-13 title padding is working fine at my end. I'm not sure but I think it's the issue related to Mac or iPhone. If it's not working there then I think the main goal is to let a user dynamically change the padding by passing a relevant field and value in the query string just like other features of the graph currently work.

@zul-m Can you please tell us which device(s) you used to test this?

**Comment by zul-m** [comment]
Hey @Kshitij978. This was tested on iPad Pro and iPhone 7

**Comment by Rituraj-13** [comment]
Hey @Kshitij978 @zul-m, I have also tested it on one of my friend's iphone. And it was fine.
