### ISSUE TITLE
BUG: No zero index on Y axis

### ISSUE THREAD

**Issue by jgphilpott** [Ashutosh00710/github-readme-activity-graph#144]
**Describe the Bug**

The Y axis scale should always start at 0 even if the lowest activity day is > zero.

**To Reproduce**

See screenshot.

**Expected behavior**

Even though the lowest activity day is 1 the Y axis scale should start from zero.

**Screenshots**

<img width="861" alt="Screen Shot 2022-09-21 at 9 48 47 AM" src="https://user-images.githubusercontent.com/4128208/191435196-43d42bb5-bf16-48ab-9323-35a807165e28.png">

**Comment by Ashutosh00710** [comment]
Graph is looking fine to me
![image](https://user-images.githubusercontent.com/42907572/191729224-28e3809b-b2e2-4692-bbd9-3953571b9bea.png)

**Comment by jgphilpott** [comment]
That's because I haven't made any commits yet today so there is a zero activity day. Once I have a commit you will see it change again. ... there must be something in the code scaling the graph between the highest value and the lowest value but it should scale between the highest value and zero.

**Comment by jgphilpott** [comment]
See the same day after adding 1 commit:

<img width="848" alt="Screen Shot 2022-09-22 at 7 33 16 PM" src="https://user-images.githubusercontent.com/4128208/191900845-ccffb59b-f4ec-403a-88d4-f2a75503d1f5.png">

**Comment by jgphilpott** [comment]
I just opened a [pull request](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/145). Look at the difference between the [main deployment](https://activity-graph.herokuapp.com/graph?username=jgphilpott&theme=github-light&area=true&hide_border=true&custom_title=Past%20Months%20Activity) and my [personal deployment](https://readme-graph-github.herokuapp.com/graph?username=jgphilpott&theme=github-light&area=true&hide_border=true&custom_title=Past%20Months%20Activity) that includes the fix.

**Comment by Ashutosh00710** [comment]
> That's because I haven't made any commits yet today so there is a zero activity day. Once I have a commit you will see it change again. ... there must be something in the code scaling the graph between the highest value and the lowest value but it should scale between the highest value and zero.

Got you

**Comment by Ashutosh00710** [comment]
#145 closes this issue
