### ISSUE TITLE
Hover effect and Styling

### ISSUE THREAD

**Issue by AbhishekTiwari23** [Ashutosh00710/github-readme-activity-graph#150]
I want to contribute to this fabulous project by adding my CSS and styling abilities. I would like to add a hover effect to the icons and text styling.
I request you allow me so that I can be a part of this initiative.

**Comment by AbhishekTiwari23** [comment]
Thanks for assigning me. I will respond as quickly as I can. 
Just a small question - Will it be counted in hacktoberfest 2022

**Comment by Ashutosh00710** [comment]
@AbhishekTiwari23 I have added the **hacktoberfest** label to this issue. Now it should be counted in **Hacktoberfest 2022**.

**Comment by AbhishekTiwari23** [comment]
<img width="1440" alt="Screenshot 2022-10-02 at 8 03 47 PM" src="https://user-images.githubusercontent.com/97469132/193475603-72a2a3a9-989c-421f-baa7-e8748ae1d1c3.png">
Hello @Ashutosh00710, I made these changes in the repo. Hope you will love this, soon I will make a pr. If you want anything other the please let me know

**Comment by AbhishekTiwari23** [comment]
All the logo has a hover effect.
