### ISSUE TITLE
NEW FEATURE:  Is it possible to add a height configuration to the chart?

### ISSUE THREAD

**Issue by wangrongding** [Ashutosh00710/github-readme-activity-graph#156]
Too high chart, feel will affect the view 🥲🥲🥲

![image](https://user-images.githubusercontent.com/42437658/194874673-b99e21f9-0399-4821-b691-dba9f3d90ed2.png)

**Comment by jmloudis** [comment]
I have opened a pull request to implement this feature, waiting for approval 

https://github.com/Ashutosh00710/github-readme-activity-graph/pull/186
