### ISSUE TITLE
BUG: the sever is down

### ISSUE THREAD

**Issue by OMEGA6403** [Ashutosh00710/github-readme-activity-graph#163]
**Describe the bug**

**To Reproduce**
Mention the steps [...]

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CBID2** [comment]
Does this bug play a role in the graph not working @OMEGA6403?

**Comment by OMEGA6403** [comment]
nah it was just down

**Comment by Ashutosh00710** [comment]
@OMEGA6403 Try now its working

**Comment by OMEGA6403** [comment]
thx
