### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by om3ga6400** [Ashutosh00710/github-readme-activity-graph#167]
**Describe the bug**
when ever i try to make a new stats thing it just loads infinitely and it does not show up on my profile

**To Reproduce**
go to https://ashutosh00710.github.io/github-readme-activity-graph/ and make new

**Comment by Vishal-beep136** [comment]
this isn't a bug it's happening because it is hosted in heroku which is now no longer provide free hosting.

**Comment by NyllRE** [comment]
@Vishal-beep136 isn't this project supported by JetBrains?

**Comment by Vishal-beep136** [comment]
@NyllRE Yeah it is but this project isn't hosted by JetBrains!
