### ISSUE TITLE
Add a footer to the graph that links back to this repository

### ISSUE THREAD

**Issue by mikeysan** [Ashutosh00710/github-readme-activity-graph#17]
**Is your feature request related to a problem? Please describe.**
When I tested your graph, I noticed that outside of GitHub there was no way for me to know:
A. Who made it, and
B. That it is open source.

**Describe the solution you'd like**
Add a footer to the generated graph that has a link back to this repository.

**Comment by Ashutosh00710** [comment]
Thanks for the idea @mikeysan we can add this feature. 

Are you interested in implementing this issue ?

**Comment by mikeysan** [comment]
I can just about do Python at the moment (still learning). :) 

Let me do the documentation stuff I spoke of in a different ticket. If this is not done by then, I will take a crack at it.

**Comment by Kshitij978** [comment]
Sure :)

**Comment by mikeysan** [comment]
Oh Great! Someone else did it :) My new job has me really busy lately.

**Comment by Ashutosh00710** [comment]
No issues @mikeysan, that's completely fine. 🙂
