### ISSUE TITLE
Changing the example in the readme to make it clearer for users

### ISSUE THREAD

**Issue by mikeysan** [Ashutosh00710/github-readme-activity-graph#18]
**Is your feature request related to a problem? Please describe.**
I would like to raise a PR and make changes regarding the section about passing my username to the url 
We discuss this [here](https://github.com/EddieJaoudeCommunity/support/issues/698) and I was invited to raise the PR to make the changes.

**Describe the solution you'd like**
Here is what I propose to do.
```md
remove - [![Ashutosh's github activity graph]
```
And then add this section only.
```md
https://activity-graph.herokuapp.com/graph?username=Ashutosh00710
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Ashutosh00710** [comment]
Thank You 🙂 for raising this issue @mikeysan, this will help us in improving the quality of this project.

Yes, @mikeysan folk the repository and make changes as per your understanding and make a PR. I will go through it. I am assigning this issue to you.

**Comment by eddiejaoude** [comment]
Awesome collaboration 💪
