### ISSUE TITLE
Theme name examples should be lowercase

### ISSUE THREAD

**Issue by luebbe** [Ashutosh00710/github-readme-activity-graph#19]
Not a big deal, but in your examples, the theme names start capitalized "Dracula", "Gruvbox", etc. but should be used all-lowercase.
"?theme=dracula". I copied the name from the example and of course it didn't work the first time ;) 
Maybe just add a "?theme=<theme_name>" line to each example.

**Comment by Ashutosh00710** [comment]
Thanks for raising the issue @luebbe, Do you want to update the documentation yourself or do you want us to update it?
