### ISSUE TITLE
How to deploy it on vercel or cyclic.app

### ISSUE THREAD

**Issue by PiyushYadav007** [Ashutosh00710/github-readme-activity-graph#191]
I tried to deploy it on both the servers. I got error on vercel but sucessful deployment on cyclic but its api is not working on that please check https://activity-graph.cyclic.app/

**Comment by fabianocouto** [comment]
Hi @PiyushYadav007, to deploy on vercel just create this file in project root directory.
https://github.com/fabianocouto/readme-activity-graph/blob/main/vercel.json
Go to https://vercel.com/dashboard and create a new project linked to your fork.
Hope this helps!

**Comment by fabianocouto** [comment]
I created a pull request for this: https://github.com/Ashutosh00710/github-readme-activity-graph/pull/195

**Comment by Ashutosh00710** [comment]
Hi @PiyushYadav007, it seems like you might be encountering an error because you haven't configured the **access token** in your environment variables. To resolve this, you can follow these instructions:

- [**Generate Personal Access Token**](https://github.com/settings/tokens/new?description=GitHub%20Readme%20Activity%20Graph)
- Go to the Cyclic Website and navigate to your project
- Click on "Variables"
- Set the token as an environment variable

![image](https://user-images.githubusercontent.com/42907572/235308351-55ca5e95-35aa-4a80-8bc2-b7846043f6c0.png)

Once you've completed these steps, the error should be resolved.

**Comment by PiyushYadav007** [comment]
> Hi @PiyushYadav007, it seems like you might be encountering an error because you haven't configured the **access token** in your environment variables. To resolve this, you can follow these instructions:
> 
> * [**Generate Personal Access Token**](https://github.com/settings/tokens/new?description=GitHub%20Readme%20Activity%20Graph)
> * Go to the Cyclic Website and navigate to your project
> * Click on "Variables"
> * Set the token as an environment variable
> 
> ![image](https://user-images.githubusercontent.com/42907572/235308351-55ca5e95-35aa-4a80-8bc2-b7846043f6c0.png)
> 
> Once you've completed these steps, the error should be resolved.

I did what you told me please check once that I have done them correct or not

**Comment by fabianocouto** [comment]
> > Hi @PiyushYadav007, it seems like you might be encountering an error because you haven't configured the **access token** in your environment variables. To resolve this, you can follow these instructions:
> > 
> > * [**Generate Personal Access Token**](https://github.com/settings/tokens/new?description=GitHub%20Readme%20Activity%20Graph)
> > * Go to the Cyclic Website and navigate to your project
> > * Click on "Variables"
> > * Set the token as an environment variable
> > 
> > ![image](https://user-images.githubusercontent.com/42907572/235308351-55ca5e95-35aa-4a80-8bc2-b7846043f6c0.png)
> > Once you've completed these steps, the error should be resolved.
> 
> I did what you told me please check once that I have done them correct or not

Hi @PiyushYadav007 !
Performe these steps:
https://github.com/fabianocouto/readme-activity-graph/tree/main#deploy-on-your-own-vercel-instance
