### ISSUE TITLE
BUG: This graph was stopped working. 

### ISSUE THREAD

**Issue by Raziur306** [Ashutosh00710/github-readme-activity-graph#197]
Recent I found this graph was not working anymore even the link of the website that was using to show the graph is no longer accessible.

**Comment by SoulNaturalist** [comment]
![image](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/58743402/c8b58dec-0a5f-44c5-b8e0-f51c70112ba5)

**Comment by cbhan0102** [comment]
<img width="323" alt="image" src="https://github.com/Ashutosh00710/github-readme-activity-graph/assets/71994698/b3486b8e-999d-44c3-9e9f-da141a9a0ae2">

**Comment by feduke-nukem** [comment]
same

**Comment by tranthaituananh** [comment]
same

**Comment by Ashutosh00710** [comment]
@Raziur306 , @SoulNaturalist , @cbhan0102 , @feduke-nukem @tranthaituananh , try this host instead

`https://github-readme-activity-graph.vercel.app/`

```md
[![Ashutosh's github activity graph](https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710)](https://github.com/ashutosh00710/github-readme-activity-graph)
```

The underlying issue is

![image](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/42907572/739296f8-b92e-48b1-84e3-0ead7ea5b2dc)

**Comment by tranthaituananh** [comment]
@Ashutosh00710 Thank you for your solution, it has resolved the issue.

**Comment by Tgentil** [comment]
## @Ashutosh00710 Thank you, this fixed my problem:
---
![Captura de tela 2023-05-24 090728](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/88681055/1c1a69bf-b829-4c1a-b78a-0213fccf67d8)

**Comment by vovod** [comment]
@Ashutosh00710  thank you so much

**Comment by andysingal** [comment]
Thanks a lot, I have made some changes to the code and now it is working
for me.

**Comment by Jommeke22** [comment]
> @Raziur306,@SoulNaturalist,@cbhan0102,@feduke-nukem @tranthaituananh,@Tgentil probeer in plaats daarvan deze host
> 
> `https://github-readme-activity-graph.vercel.app/`
> 
> ```
> [![Ashutosh's github activity graph](https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710)](https://github.com/ashutosh00710/github-readme-activity-graph)
> ```
> 
> Het onderliggende probleem is
> 
> ![afbeelding](https://private-user-images.githubusercontent.com/42907572/240528841-739296f8-b92e-48b1-84e3-0ead7ea5b2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDc2OTMsIm5iZiI6MTcyMDYwNzM5MywicGF0aCI6Ii80MjkwNzU3Mi8yNDA1Mjg4NDEtNzM5Mjk2ZjgtYjkyZS00OGIxLTg0ZTMtMGVhZDdlYTViMmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEwMjk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczM2Y2YmUxNDRlN2ZhZDY5Nzc4OTI5NTBlOGFiZGQ0MDU1ZWYxNzE1YjRmNGE4Y2Y1YjFjZWU3ZGYwN2I5ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T8_m52hzS7k-8ofjWRdLf6MW0n_svWNe6hkZCvvGp5c)

**Comment by Tgentil** [comment]
> > @Raziur306,@SoulNaturalist,@cbhan0102,@feduke-nukem @tranthaituananh,@Tgentil probeer in plaats daarvan deze host
> > `https://github-readme-activity-graph.vercel.app/`
> > ```
> > [![Ashutosh's github activity graph](https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710)](https://github.com/ashutosh00710/github-readme-activity-graph)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Het onderliggende probleem is
> > ![afbeelding](https://private-user-images.githubusercontent.com/42907572/240528841-739296f8-b92e-48b1-84e3-0ead7ea5b2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDc2OTMsIm5iZiI6MTcyMDYwNzM5MywicGF0aCI6Ii80MjkwNzU3Mi8yNDA1Mjg4NDEtNzM5Mjk2ZjgtYjkyZS00OGIxLTg0ZTMtMGVhZDdlYTViMmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEwMjk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczM2Y2YmUxNDRlN2ZhZDY5Nzc4OTI5NTBlOGFiZGQ0MDU1ZWYxNzE1YjRmNGE4Y2Y1YjFjZWU3ZGYwN2I5ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T8_m52hzS7k-8ofjWRdLf6MW0n_svWNe6hkZCvvGp5c)

@Jommeke22 ,  thanks for pointing out the ongoing issues with the graph. The issue you're referencing has indeed been closed, this issue can be resolved by deploying a personal instance of the activity graph. If you set up your own instance following [these instructions](https://github.com/Ashutosh00710/github-readme-activity-graph?tab=readme-ov-file#deploy-on-your-own-vercel-instance), you should find that it resolves the problem for you as well. Here’s an example with my own instance: ![my Graph](https://github-readme-activity-graph.vercel.app/graph?username=Tgentil&bg_color=1c1917&color=ffffff&line=0891b2&point=ffffff&area_color=1c1917&area=true&hide_border=true&custom_title=GitHub%20Commits%20Graph)

**Comment by Cezarsilvasantosotaner** [comment]
https://github.com/Ashutosh00710/github-readme-activity-graph.git

**Comment by Cezarsilvasantosotaner** [comment]
https://github.com/Ashutosh00710/github-readme-activity-graph.git
