### ISSUE TITLE
Bug Report - Commits Graph Card Not Displaying Properly

### ISSUE THREAD

**Issue by Tgentil** [Ashutosh00710/github-readme-activity-graph#201]
**Describe the bug**
The card for the commits graph is not functioning properly. When I include the graph card in my GitHub profile README, only the alt text is displayed instead of the actual graph. Additionally, clicking on the alt text leads to an "Error Fetching Resource" page instead of displaying the image of the graph. I have a screenshot of how the graph appears in the README that I will attach here. 

The code I used to include the graph card in my GitHub profile is:

```
<img height="200em" src="https://github-readme-activity-graph.vercel.app/graph?username=Tgentil&bg_color=1c1917&color=ffffff&line=0891b2&point=ffffff&area_color=1c1917&area=true&hide_border=true&custom_title=GitHub%20Commits%20Graph" alt=" My github activity graph">
```

**To Reproduce**
1. Go to my GitHub profile README.   [![GitHub](https://img.shields.io/badge/Visit-My%20Profile-0891B2?style=flat-square&logo=github)](https://github.com/Tgentil)
2. Look for the code snippet mentioned above.
3. Observe that only the alt text is displayed instead of the graph.
4. Click on the alt text and observe that it leads to an "Error Fetching Resource" page.

**Expected behavior**
I expected the graph card to display the actual graph of my GitHub commits activity in my profile README.

**Screenshots**
I will attach a screenshot of the issue showing how the graph card appears in the README.
![error](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/88681055/8d0fad3a-1e9a-4e15-9fed-d64cb65c680c)
![Error link](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/88681055/b15aae18-824b-4f11-b5b9-c003bdec8943)

**Desktop:**
- OS: Windows 11
- Browser: Google Chrome
- Version: 114.0.5735.110 (Official Build) (64-bit)

**Smartphone:**
- Device: iPhone XS 64GB
- OS: iOS
- Browser: Safari

**Additional context**
I am experiencing the same issue on both my desktop (Windows) and smartphone (iPhone XS).

**Comment by Tgentil** [comment]
Apologies for the duplicate issue, but it seems that I have encountered a similar or equal problem as the issue #200. The commits graph card in my profile is not displaying properly, showing only the alt text. Clicking on the alt text leads to an "Error Fetching Resource" page instead of displaying the image. I have also provided additional information regarding my device and browser versions.

**Comment by Ashutosh00710** [comment]
Hi @Tgentil, It is visible to me. I don't know what happened at your end.
![image](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/42907572/a2c699ae-254d-4eda-bfdc-631c50de8017)

**Comment by Ashutosh00710** [comment]
Maybe there was some temporary issue at hosting service provider end. Closing this issue
