### ISSUE TITLE
BUG: can't show the contribution I made from public repo

### ISSUE THREAD

**Issue by ThunderCarver** [Ashutosh00710/github-readme-activity-graph#204]
**Describe the bug**
When I fork a repo like named username/ABC to my own repo named myusername/ABC
and I clone it to my local machine and make some improvements.
However when I push those updates to my forked repo myusername/ABC:branch_x, those updates cannot show in the activity graph.

**To Reproduce**
Just like I described above

**Expected behavior**
the acitivity graph should show the changes I made in these forked repositories.

**Screenshots**
not available now

**Desktop (please complete the following information):**
 - OS: [macOS, Ubuntu]
 - Browser [safari]
 - Version [safari Version 16.6]

**Comment by Ashutosh00710** [comment]
@ThunderCarver the point is that the graph updates every 30 minutes when you refresh your page. Graph is not updating in realtime. We implemented things this way to avoid a ton of requests traffic to our server

**Comment by ThunderCarver** [comment]
Thanks for your reply.

yet, the problem is not like you described. I would like to show you some screenshots to help you understand what happened.
First, I commit some work to my remote repo
![image](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/27229985/31b7840b-e48a-4c8f-be0a-915e4ebec43d)


and my remote url is shown by running  “git remote -v” command:
![image](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/27229985/2b66e7df-e26e-4dda-8ffd-c0bba0f59d39)



but they didn’t show in my contribution graph far beyond 30 mintues, and following is my contribution graph:
![image](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/27229985/fc5bb133-0db0-4339-85dc-bf89441411c3)

as you can see day 21st has no contribution. 

How can I set up to fix this problem.

**Comment by ThunderCarver** [comment]
Thanks for your reply.

yet, the problem is not like you described. I would like to show you some screenshots to help you understand what happened.
First, I commit some work to my remote repo
￼

and my remote url is shown by running  “git remote -v” command:
￼


but they didn’t show in my contribution graph far beyond 30 mintues, and following is my contribution graph:
￼
as you can see day 21st has no contribution. 

How can I set up to fix this problem. 
At last, so much thanks for your quick reply.

**Comment by Ashutosh00710** [comment]
Hmm ... 🤔💭 strange, I have to look into this. Right now I don't know the exact cause of this bug but when I visited your profile the commit was clearly visible.

Here is a screenshot
<img width="1440" alt="Screenshot 2023-09-22 at 10 40 42 PM" src="https://github.com/Ashutosh00710/github-readme-activity-graph/assets/42907572/84dcacf4-399f-4e61-9dac-0fac5a4cf7c5">

**Comment by ThunderCarver** [comment]
Oops, sorry for the late reply.
The 2 contributions shown on 21st is not from the commits in the forked repo rather than my other private repo. Actually, any commit I gitted cannot show in my contribution graph. And perhaps it related with forked repo. I find a rul(https://github.com/anuraghazra/github-readme-stats#top-languages-card)/[Warning part] that looks similar. Hope this may provide some tips to you.
![image](https://github.com/Ashutosh00710/github-readme-activity-graph/assets/27229985/11331153-2fa6-4854-9ead-723413afc49a)

**Comment by ThunderCarver** [comment]
Hey, do you figure out what cause the commits I push to a **forked repo** not shown in contribution graph? 
Thanks 😄

**Comment by Ashutosh00710** [comment]
@ThunderCarver forked commits are not going to be considered as you commits that's why it is not showing up there. For more info refer [this](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commits) and check the 2nd point

**Comment by ThunderCarver** [comment]
Oh, thanks for your reply! It really solves my problem and confusion. Thanks again
