### ISSUE TITLE
Can anyone tell me why this is not working?

### ISSUE THREAD

**Issue by PiyushYadav007** [Ashutosh00710/github-readme-activity-graph#205]
Can anyone tell me why this is not working?

https://piyushyadav007.github.io/github-readme-activity-graph/

**Comment by Ashutosh00710** [comment]
In your forked [repo](https://github.com/PiyushYadav007/github-readme-activity-graph) inside [`script.js`](https://github.com/PiyushYadav007/github-readme-activity-graph/blob/main/script.js) at line: [50](https://github.com/PiyushYadav007/github-readme-activity-graph/blob/d141aee27ae93df78ff07ab4dd010f43b9095c2b/script.js#L50) and [118](https://github.com/PiyushYadav007/github-readme-activity-graph/blob/d141aee27ae93df78ff07ab4dd010f43b9095c2b/script.js#L118) has incorrect domain to fetch the graph data

The domain is changed from `github-readme-activity-graph.cyclic.app` to `github-readme-activity-graph.vercel.app`.
[Reason for change](https://github.com/Ashutosh00710/github-readme-activity-graph/issues/197)

**Comment by Kshitij978** [comment]
@PiyushYadav007 did @Ashutosh00710 's solution worked for you? Please let us know so that we can close this issue.

**Comment by Piyush-rjit** [comment]
> @PiyushYadav007 did @Ashutosh00710 's solution worked for you? Please let us know so that we can close this issue.

Yes
