### ISSUE TITLE
NEW FEATURE: Customize the duration

### ISSUE THREAD

**Issue by Mahesh-Langote** [Ashutosh00710/github-readme-activity-graph#208]
I'd like to request the addition of a customization option for the appearance of individual days on the GitHub contribution graph.

**Comment by shraf** [comment]
i'm suggesting to have option to specify the exact duration, for example from 1/3/2022 to 1/5/2022 @Mahesh-Langote

**Comment by Joknaa** [comment]
Yes that would be reaally appreciated

**Comment by Ashutosh00710** [comment]
@Mahesh-Langote @shraf @Joknaa 
This feature is now implemented 🚀 

**Use it like:** `https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710&from=2022-09-21&to=2022-10-21&area=true`

Varcel is facing some issue on their end [refer this](https://www.vercel-status.com/). So it will take time to reflect on production. But if you have self-hosted this server then you can take a fork and redeploy, it should work fine

**Comment by Ashutosh00710** [comment]
duplicate of #87

**Comment by Ashutosh00710** [comment]
@Mahesh-Langote @shraf @Joknaa  it live now

`https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710&from=2022-09-21&to=2022-10-21&area=true`
![](https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710&from=2022-09-21&to=2022-10-21&area=true)
