### ISSUE TITLE
NEW FEATURE: Option to hide the grid and change its color in the activity graph

### ISSUE THREAD

**Issue by garvit-exe** [Ashutosh00710/github-readme-activity-graph#212]
**Problem**
I can't find an option to hide the grid patterns (the dotted lines) in the background of the activity graph.

**Solution**
Please add an option where you can add `hide_grid=true` in the URL of the graph to hide these dotted lines and also add '`grid_color=HEX_CODE` (without #)' option to set the color of these lines.

**Additional context**
<img width="1051" alt="SCR-20240511-ukrt" src="https://github.com/Ashutosh00710/github-readme-activity-graph/assets/122175234/449d2c94-3ab4-4cd1-a1a8-0b4ac33dfb16">

**Comment by Ashutosh00710** [comment]
@garvit-exe this feature is now available in production.

use it like: `https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710&from=2022-09-21&to=2022-10-21&area=true&grid=false`

It will look like this 👇🏼 (for more info refer docs)

![](https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710&from=2022-09-21&to=2022-10-21&area=true&grid=false)
