### ISSUE TITLE
> @Raziur306,@SoulNaturalist,@cbhan0102,@feduke-nukem @tranthaituananh,@Tgentil probeer in plaats daarvan deze host

### ISSUE THREAD

**Issue by Jommeke22** [Ashutosh00710/github-readme-activity-graph#214]
> @Raziur306,@SoulNaturalist,@cbhan0102,@feduke-nukem @tranthaituananh,@Tgentil probeer in plaats daarvan deze host
> 
> `https://github-readme-activity-graph.vercel.app/`
> 
> ```
> [![Ashutosh's github activity graph](https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710)](https://github.com/ashutosh00710/github-readme-activity-graph)
> ```
> 
> Het onderliggende probleem is
> 
> ![afbeelding](https://private-user-images.githubusercontent.com/42907572/240528841-739296f8-b92e-48b1-84e3-0ead7ea5b2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDc2OTMsIm5iZiI6MTcyMDYwNzM5MywicGF0aCI6Ii80MjkwNzU3Mi8yNDA1Mjg4NDEtNzM5Mjk2ZjgtYjkyZS00OGIxLTg0ZTMtMGVhZDdlYTViMmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEwMjk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczM2Y2YmUxNDRlN2ZhZDY5Nzc4OTI5NTBlOGFiZGQ0MDU1ZWYxNzE1YjRmNGE4Y2Y1YjFjZWU3ZGYwN2I5ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T8_m52hzS7k-8ofjWRdLf6MW0n_svWNe6hkZCvvGp5c)

_Originally posted by @Jommeke22 in https://github.com/Ashutosh00710/github-readme-activity-graph/issues/197#issuecomment-2220137960_

**Comment by Tgentil** [comment]
@Jommeke22 This issue can be resolved by deploying a personal instance of the activity graph. If you set up your own instance following [these instructions](https://github.com/Ashutosh00710/github-readme-activity-graph?tab=readme-ov-file#deploy-on-your-own-vercel-instance), you should find that it resolves the problem for you as well. Here’s an example with my own instance: ![my Graph](https://github-readme-activity-graph.vercel.app/graph?username=Tgentil&bg_color=1c1917&color=ffffff&line=0891b2&point=ffffff&area_color=1c1917&area=true&hide_border=true&custom_title=GitHub%20Commits%20Graph)

**Comment by Ashutosh00710** [comment]
Graphs are working totally fine on our end, the issue mentioned in the comment by @Jommeke22 was very old. I am closing this issue.
