### ISSUE TITLE
Add a demo link

### ISSUE THREAD

**Issue by Ashutosh00710** [Ashutosh00710/github-readme-activity-graph#32]
Add a demo link in the documentation so that users can see their graphs in action, on their browser.

**Comment by Vaibhav-afk** [comment]
I can do this

**Comment by Vaibhav-afk** [comment]
I can do this

**Comment by KG-1510** [comment]
Can I please work on this issue?

**Comment by vikas-ukani** [comment]
@Ashutosh00710 

 I just use it and *designed my Github Profile.*
 
 Here is the *URL*  [**https://github.com/vikas-ukani**](https://github.com/vikas-ukani)

--- 

Looks so wonderful, Yeh 🥇
