### ISSUE TITLE
[Feature] Hide border option

### ISSUE THREAD

**Issue by DenverCoder1** [Ashutosh00710/github-readme-activity-graph#51]
It would be useful to add a feature for either changing the border color or adding a `hide_border` parameter.

Other stats cards such as [Streak Stats](https://github.com/DenverCoder1/github-readme-streak-stats) and [Readme Stats](https://github.com/anuraghazra/github-readme-stats) support this flag.

### Activity Graph alongside other readme stats cards:

![image](https://user-images.githubusercontent.com/20955511/108357550-41841200-71f6-11eb-8e56-4e8fc1d4a34a.png)

**Comment by Kshitij978** [comment]
Hello, @DenverCoder1 Thank you for using github readme activity graph and raising this issue. This feature will definitely enhance the quality of the graph. 

Are you interested in implementing this feature or you want us to do so?

**Comment by DenverCoder1** [comment]
Hi, @Kshitij978. I think I can give a try.

**Comment by Kshitij978** [comment]
That's great! Go for it ✨ I'm assigning this issue to you.
