### ISSUE TITLE
NEW FEATURE REQUEST

### ISSUE THREAD

**Issue by raklaptudirm** [Ashutosh00710/github-readme-activity-graph#64]
**Is your feature request related to a problem? Please describe.**
The dates are always numbered 1-31

**Describe the solution you'd like**
Instead, they could show the actual dates, like 28, 29, 30, 1, instead of just numbering 1-31

**Comment by jgphilpott** [comment]
I like the idea!

**Comment by Ashutosh00710** [comment]
@jgphilpott interested in working on this feature?

**Comment by jgphilpott** [comment]
@Ashutosh00710 perhaps some weekend next month I could look into it, a little to busy for it right now.

**Comment by Ashutosh00710** [comment]
Sure @jgphilpott 🙂

**Comment by jgphilpott** [comment]
@Ashutosh00710 do you think you could point me to a line as a starting point? I'm not 100% familiar with the code yet..
