### ISSUE TITLE
NEW FEATURE REQUEST - Change and/or Hide Title

### ISSUE THREAD

**Issue by jgphilpott** [Ashutosh00710/github-readme-activity-graph#65]
Would it be possible to have an option to change and/or hide the title?

**Comment by Ashutosh00710** [comment]
@jgphilpott thanks for raising this issue 🙂

> Would it be possible to have an option to change and/or hide the title?
Yes, it is possible. 

Are you interested in working on this feature or you want us to implement so ?

**Comment by jgphilpott** [comment]
@Ashutosh00710 I suppose I could try to implement it.. I'm not 100% sure what to do tho..

I browsed the **src folder** and I see the options in the card class in the **GraphCards file**, I guess those would need to be updated. I also looked at the **createChart file** but wasn't quite sure how to modify the title.

It would be nice to figure it out because I had a few other things I was interested in adding, like font size option.

**Comment by Ashutosh00710** [comment]
> I'm not 100% sure what to do tho..

[This](https://github.com/Ashutosh00710/github-readme-activity-graph/blob/b6cb001e205e7cea5f45f6a4529dd7eb1727fad0/src/utils.ts#L74) is the line which is responsible for the title. Trace where this parameter is going to get a better idea about the title.

> createChart file but wasn't quite sure how to modify the title

Title has nothing to do with this file. This file is just returning the graph svg

> I had a few other things I was interested in adding, like font size option.

Can check [`svg.ts`](https://github.com/Ashutosh00710/github-readme-activity-graph/blob/b6cb001e205e7cea5f45f6a4529dd7eb1727fad0/src/svgs.ts) for styling options.

Drop a comment if you have any queries about the code ? I am here to hep you 🙂
Thanks for showing interest in contributing to this project.

**Comment by jgphilpott** [comment]
Okay thanks, I will take a look at it this weekend when I have a little more time.

**Comment by Ashutosh00710** [comment]
Sure 🚀

**Comment by jgphilpott** [comment]
Okay i've put in a [pull request](https://github.com/Ashutosh00710/github-readme-activity-graph/pull/69).
