### ISSUE TITLE
BUG-Text color not changing

### ISSUE THREAD

**Issue by Ishaan-11** [Ashutosh00710/github-readme-activity-graph#66]
**Describe the bug**
As i select a Text color it does not reflect on the graph

**To Reproduce**
step-1: enter your username
step-2: try changing text color

**Expected behavior**
Text color of graph should change accordingly

**Screenshots**
![image](https://user-images.githubusercontent.com/51826621/119540590-37505180-bdab-11eb-886a-c69b819f5252.png)

**Comment by Ashutosh00710** [comment]
Thanks @Ishaan-11 🙂 for raising this issue. 

The issue has been resolved with commit 8403094 ✅
