### ISSUE TITLE
BUG Label Alignment on Safari

### ISSUE THREAD

**Issue by EmperorYP7** [Ashutosh00710/github-readme-activity-graph#81]
**Describe the bug**
The x-axis labels are not being rendered correctly due to some reason.

**To Reproduce**
Look at the graph

**Expected behavior**
The axis labels should be properly aligned.

**Screenshots**
<img width="856" alt="Screenshot 2021-09-04 at 9 15 55 PM" src="https://user-images.githubusercontent.com/62606998/132100388-77d942cb-e72d-4979-905a-e6bb54822e2b.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] Version 14.1.2

**Additional context**

NA

**Comment by Kshitij978** [comment]
Hi! @EmperorYP7 Thank you for raising this issue. We are very sorry for the inconvenience. It's a cross browser compatibility issue and we are looking into it.

**Comment by EmperorYP7** [comment]
Update: It seems to be fixed for now. Maybe #80 was reverted.

**Comment by Ashutosh00710** [comment]
Update: Feature #80 is redeployed. Unfortunately, we don't have any solution for Safari.
