### ISSUE TITLE
[Feature request] Custom timeframe

### ISSUE THREAD

**Issue by ThatOneCalculator** [Ashutosh00710/github-readme-activity-graph#87]
Being able to add a timeframe (like a start and end date or time range) would be useful if I'd like to show a couple months or even a year

**Comment by ricar2ce** [comment]
any news about this topic?

**Comment by Ashutosh00710** [comment]
@ThatOneCalculator and @ricar2ce 
This feature is now implemented 🚀 

**Use it like:** `https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710&from=2022-09-21&to=2022-10-21&area=true`

Varcel is facing some issue on their end [refer this](https://www.vercel-status.com/). So it will take time to reflect on production. But if you have self-hosted this server then you can take a fork and redeploy, it should work fine.

**Comment by Ashutosh00710** [comment]
@ThatOneCalculator @ricar2ce  its live now

`https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710&from=2022-09-21&to=2022-10-21&area=true`
![](https://github-readme-activity-graph.vercel.app/graph?username=Ashutosh00710&from=2022-09-21&to=2022-10-21&area=true)
