### ISSUE TITLE
BUG: Dates are not diagonal when viewing from an iPhone

### ISSUE THREAD

**Issue by KayvT** [Ashutosh00710/github-readme-activity-graph#93]
**The Bug**
The dates that are supposed to be on the X-axis are diagonal and overlapping with the graph itself and the graph's title.

**To Reproduce:**
Visit my profile, use the dev tools and then switch the view mode to an iphone 

**Expected behavior**
Should be normally aligned across the X-axis

**Screenshots**
![ImageXX](https://user-images.githubusercontent.com/40730865/140605957-d282c94f-bada-4526-9bdf-d8e7810ddd45.jpeg)

 - Device: iPhone 8+
 - OS:  iOS 15
 - Browser: Native GitHub App
 - Version 1.38.0

**Comment by Ashutosh00710** [comment]
We are no longer supporting diagonal dates, due to limitations in safari
